name: Daily runs
on:
  schedule:
    - cron: '0 8 * * 1'  # 7 am UTC on mondays
  push:
    paths:
      - '.github/workflows/weekly.yml'
    # - 'crispybeefbot.py'

jobs:
  crispy-beef-check:
    name: "Check Clausiusbar for Cripy Beef"
    runs-on: ubuntu-latest
    env:
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@d05808540d968a55ca33c798e0661fb98f533c73
        with:
          micromamba-version: 1.5.10-0
          cache-env: true
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.PYTHON_VERSION }}
      - name: Run beefscripy
        shell: bash -el {0}
        run: python crispybeefbot.py

  keep-cron-alive:
    name: Empty commit to keep the cronjob alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@2a8ae70f39b79fb50659d17ccc6f372f461813b2