name: Daily runs
on:
  schedule:
    - cron: '0 8 * * 1'  # 8 am on mondays
  push:
    paths:
    - '.github/workflows/weekly.yml'

jobs:
  crispy-beef-check:
    name: "Check Clausiusbar for Cripy Beef"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          environment-file: environment.yml
          init-shell: bash
      - name: Run beefscripy
        shell: bash -el {0}
        run: python crispybeefbot.py
